### ISSUE TITLE
Portable package without install

### ISSUE THREAD

**Issue by kowith337** [edward-ly/stepmania-song-manager#11]
Can you release full package without setup (into `%appdata%` and/or `%localappdata%`) file?
Just extract and launch freely without append in program and features (even it's just installed for current user)

**Comment by edward-ly** [comment]
If I can figure out how to make a portable version, sure, but I am also using the app data folder as the default location for storing the downloaded songs. Where do you think the songs should be downloaded to if not that folder?

**Comment by kowith337** [comment]
Currently for my setup is store SM, Etterna, RIO, etc. to another HDD/SSD or partition, all of them are not setup directly but extract setup file and launch instead.

**Comment by edward-ly** [comment]
By "program folder", you mean the folder where the app is running? Sounds reasonable enough.

**Comment by edward-ly** [comment]
Sorry for the wait, but the portable app has been added and will be available in the next version (most likely 0.4.0)! The `%appdata%` folder is still required to run the app, though, so I left the default download path the same. You always have the option of changing the path manually, and I don't want the possibility of a random default path accidentally deleting any user data either.

**Comment by edward-ly** [comment]
Closing now that version 0.4.0 is finally published.
