### ISSUE TITLE
Error: Uncaught Error: certificate has expired

### ISSUE THREAD

**Issue by Logobot757** [edward-ly/stepmania-song-manager#13]
Every time i try to download a pack, this happens. Its infuriating.
![Screenshot (1)](https://user-images.githubusercontent.com/74375048/147624132-9f3ae2c0-510c-4914-9ff0-1a05856df854.png)
.

**Comment by edward-ly** [comment]
This is, indeed, an urgent matter. I'll look for a fix as soon as I can.

**Comment by Logobot757** [comment]
Thank you.

**Comment by edward-ly** [comment]
Now fixed and pushed to version 0.4.0.
